version: "3"

services:
  app:
    container_name: todo_app
    build: .
    ports:
      - "80:80"
    volumes:
      - "./src:/app/app"
    environment:
      LOG_LEVEL: info
    command: "/start-reload.sh"
