version: "3"

services:
  app:
    container_name: todo_app
    build: .
    ports:
      - "80:80"
    volumes:
      - "./app:/app/app"
      - "./tests:/app/tests"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: todo
      LOG_LEVEL: info
      APP_LOG_LEVEL: DEBUG
      USER_POOL_ID: $userPoolId
      APP_CLIENT_ID: $clientId
    command: "/start-reload.sh"
    networks:
      - todo

  db:
    image: postgres:latest
    container_name: todo_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
      TZ: Asia/Tokyo
    volumes:
      - ./scripts/init_db:/docker-entrypoint-initdb.d
    networks:
      - todo

networks:
  todo: null
